# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: damiano004
# "service" is the name of this project. This will also be added to your AWS resource names.
service: HospitalAPI

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role: arn:aws:iam::814283364960:role/LabRole

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
          
  lista-pz:
    handler: pazienti.listaPz
    events:
      - httpApi:
          path: /lista-pz
          method: get

  accetta-pz:
    handler: pazienti.accettaPz
    events:
      - httpApi:
          path: /accetta-pz
          method: post
          
  trasferisci-pz:
    handler: pazienti.trasferisciPz
    events:
      - httpApi:
          path: /trasferisci-pz/{id}
          method: put

  dimetti-pz:
    handler: pazienti.dimettiPz
    events:
      - httpApi:
          path: /dimetti-pz/{id}
          method: delete
plugins:
  - serverless-offline